name: Conformance Delegated IPAM

# TODO: update this to run on a schedule.
on: workflow_dispatch

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    name: 'Setup & Test'
    env:
      job_name: 'Setup & Test'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Generate conflist for each node
        run: |
          createConflist() {
            file=$1
            subnet=$2

            cat <<EOF > $file
            {
              "cniVersion": "0.3.1",
              "name": "cilium",
              "plugins": [
                {
                  "type": "cilium-cni",
                  "enable-debug": true,
                  "log-file": "/var/log/cilium-cni.log",
                  "ipam": {
                    "type": "host-local",
                    "ranges": [
                      [{"subnet": "$subnet"}]
                    ]
                  }
                }
              ]
            }
          EOF
          }

          createConflist "kind-control-plane-delegated-ipam.conflist" 10.244.1.0/24
          createConflist "kind-worker-delegated-ipam.conflist" 10.244.2.0/24
          createConflist "kind-worker2-delegated-ipam.conflist" 10.244.3.0/24

      - name: Generate kind config
        run: |
          cat <<EOF > kind-config-delegated-ipam.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
              # Disable kube-controller-manager allocate-node-cidrs to avoid mismatch between
              # the node podCIDR assigned by KCM and the CIDR configured for the host-local IPAM plugin.
              kubeadmConfigPatches:
                - |
                  apiVersion: kubeadm.k8s.io/v1beta3
                  kind: ClusterConfiguration
                  controllerManager:
                    extraArgs:
                      allocate-node-cidrs: "false"
              extraMounts:
                - hostPath: kind-control-plane-delegated-ipam.conflist
                  containerPath: /etc/cni/net.d/05-cilium.conflist

            - role: worker
              extraMounts:
                - hostPath: kind-worker-delegated-ipam.conflist
                  containerPath: /etc/cni/net.d/05-cilium.conflist

            - role: worker
              extraMounts:
                - hostPath: kind-worker2-delegated-ipam.conflist
                  containerPath: /etc/cni/net.d/05-cilium.conflist

          networking:
            disableDefaultCNI: true
            podSubnet: "10.244.0.0/16"
            serviceSubnet: "10.245.0.0/16"
          EOF

      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          cluster_name: "kind"
          config: kind-config-delegated-ipam.yaml
          wait: 0 # The control-plane never becomes ready, since no CNI is present

      - name: Wait for nodes to become ready
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
          kubectl get nodes -oyaml

      # Delegated IPAM requires direct routing, and we can't use autoDirectNodeRoutes or BGP because
      # Cilium isn't aware of the pod CIDR for each node.
      # So use `ip route add` to ensure pod traffic is routed to the correct node.
      - name: Configure routes
        run: |
          addPodCIDRRouteToNode() {
            cidr=$1
            node=$2
            nodeIP=$(kubectl get node $node -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
            echo "adding route from $cidr via $nodeIP"
            sudo ip route add $cidr via $nodeIP
          }

          echo "Current routes:"
          ip route

          echo "Configuring routes from podCIDR to node:"
          addPodCIDRRouteToNode 10.244.1.0/24 kind-control-plane
          addPodCIDRRouteToNode 10.244.2.0/24 kind-worker
          addPodCIDRRouteToNode 10.244.3.0/24 kind-worker2

          echo "Updated routes:"
          ip route

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@62bd4511031211b50a4623870955a5ad27b43e3b # v0.16.16
        with:
          go-mod-directory: "."

      - name: Install Cilium
        run: |
          # Cilium configured with delegated IPAM mode.
          # * Set cni.customConf=true since conflist is configured using host mount into kind nodes.
          # * Delegated IPAM requires direct routing mode.
          # * Delegated IPAM is incompatible with all options that require cilium-agent to assign itself an IP address,
          #    so set local-router-ipv4 and endpointHealthChecking.enabled=false.
          # * Use BPF masquerade with ipMasqAgent.enabled=true because iptables masquerade (enable-ipv4-masquerade=true)
          #    matches on source IP in the node pod CIDR, which isn't available to Cilium in delegated IPAM mode.
          cilium install \
            --set ipam.mode=delegated-plugin \
            --set cni.customConf=true \
            --set routingMode=native \
            --set ipv4NativeRoutingCIDR=10.244.0.0/16 \
            --set endpointRoutes.enabled=true \
            --set endpointHealthChecking.enabled=false \
            --set extraArgs[0]="--local-router-ipv4=169.254.23.0" \
            --set enableIPv4Masquerade=true \
            --set bpf.masquerade=true \
            --set ipMasqAgent.enabled=true \
            --set nodePort.enabled=true

      - name: Wait for Cilium status to be ready
        run: |
          cilium status --wait
          kubectl -n kube-system get pods -owide

      - name: Cilium connectivity test
        run: |
          cilium connectivity test
